# Proposal

## Research topic

We will analyze the dataset from three main perspectives. Firstly, we will select some purchase volume indicators to show people's drinking preferences. Then, we will analyze whether preferences differ between regions in Iowa from a geographic perspective. Finally, we will analyze whether people's alcohol consumption follows the seasons from a temporal perspective.

**People's drinking preferences**

We will use attributes such as Category Name, Sale (Dollars), etc. to represent people's consumption preferences. For example, we will find out which liquors are the most popular in Iowa and which are the least popular. Which type of alcohol had the highest turnover in 2019. Whether people buy alcohol in large or small quantities.

**Regional perspective**

In addition, detailed geographic information is given in the dataset, which includes the store address, the county and the city where it is located. We want to study the differences in people's alcohol consumption in different regions. For example, at which administrative level is there an obvious difference in alcohol consumption, the City level or the County level or the Zipcode level?

**Timing perspective**

Finally, our dataset also records the time of each alcoholic beverage purchase, with data accurate to the day. We will use the Date to explore whether Iowa residents' consumption of alcohol is influenced by season. Whether there are significant cyclical variations in people's consumption of alcohol, etc.

## Data availability

In this [2019 Iowa Liquor Sales dataset](https://data.iowa.gov/Sales-Distribution/2019-Iowa-Liquor-Sales/38x4-vs5h), there are very few missing values. There are as many as 24 attributes, which include Date of consumption, Store Name, Category Name, Vendor name and more, detailing every single alcohol consumption. In addition, this dataset is rich in Catigorical Data as well as Numerical Data, and we can use as many kinds of charts as possible to explore the data in the subsequent analysis.

The dataset was collected from grocery stores, liquor stores, convenience stores and so on which has Class E liquor license. If we encounter some questions, we can simply submit contact request form in Iowa government website. How to use the data? We can export it as csv file and import to Rstudio. The dataset consists of 2.38 million points with 24 columns. In this particular project, we will discard the identification information such as "Invoice Number", "Store Adress", "Item Number", etc.

In the next modules, Catigorical Data and Numerical Data, we analyze each of the attributes contained in the database, their size, origin and some characteristics.

### Catigorical Data

**Date:** from 01/02/2019 to 12/31/2019. There are some missing days. 264 days in total.

**Store Number:** Each store is associated with a unique store number. 1748 store numbers in total.

**Store Name:** Name of each store. 1759 store names in total.

**Address:** Address of stores. 1751 unique addresses in total and 4764 NaN values out of 2380345 rows.

**City:** Cities where the stores are located. 428 stores in total and 4764 NaN values out of 2380345 rows.

**Zip Code:** Zip codes associated with the store locations. 462 zip codes in total and 4764 NaN values out of 2380345 rows.

**Store Location:** longitude and latitude of store locations. 1611 unique geographic coordinates and 219390 NaN values out of 2380345 rows.

**County Number:** Iowa county number of the counties where the stores are located. 99 unique counties in total and 4764 NaN values out of 2380345 rows.

**County:** Iowa counties where the stores are located. 99 unique counties in total and 4764 NaN values out of 2380345 rows.

**Category:** Category codes the liquor is associated with. 53 unique categories of liquor and 2918 NaN values out of 2380345 rows.

**Category Name:** Categories of liquor. 53 unique categories of liquor and 2918 NaN values out of 2380345 rows.

**Vendor Number:** Vendor number of the company for the brand of liquor. 191 unique vendor numbers and 1 NaN value out of 2380345 rows.

**Vendor Name:** Vendor name of the company for the brand of liquor. 192 unique vendor names and 1 NaN value out of 2380345 rows.

**Item Number:** Item number associated with each liquor product. 4008 unique item numbers in total and no missing values.

**Item Description:** Description of each liquor item such as "HAWKEYE VODKA" and "RUSSELL'S RESERVE 10YR". 3475 descriptions in total and no missing values.

### Numerical Data

**Pack** (The number of bottles in a case for the liquor ordered) column Pack has a mean of 12.43, a standard deviation of 8.11, a min of 1.0, a median of 12.0, and a max of 48.0.

**Bottle Volume** (Volume of each liquor bottle ordered in milliliters) column Bottle Volume (ml) has a mean of 876.64, a standard deviation of 521.43, a min of 20.0, a median of 750.0, and a max of 6000.0

**State Bottle** Cost (The amount that the Alcoholic Beverages Division paid for each bottle of liquor ordered) column State Bottle Cost has a mean of 10.34, a standard deviation of 8.57, a min of 0.89, a median of 8.25, and a max of 1749.12

**Bottles Sold** (The number of bottles of liquor ordered by the store) column Bottles Sold has a mean of 11.28, a standard deviation of 31.31, a min of 1.0, a median of 6.0, and a max of 6750.0

**State Bottle Retail** (The amount the store paid for each bottle of liquor ordered) column State Bottle Retail has a mean of 15.52, a standard deviation of 12.86, a min of 1.34, a median of 12.38, and a max of 2623.68

**Sale** (Total cost of liquor order (number of bottles multiplied by the state bottle retail) column Sale (Dollars) has a mean of 146.71, a standard deviation of 487.18, a min of 1.34, a median of 75.36, and a max of 78435.0

**Volume Sold** (Total volume of liquor ordered in liters) column Volume Sold (Liters) has a mean of 9.37, a standard deviation of 38.24, a min of 0.02, a median of 4.8, and a max of 11812.5

**Volume Sold:** column Volume Sold (Gallons) has a mean of 2.47, a standard deviation of 10.1, a min of 0.0, a median of 1.26, and a max of 3120.53. This column should be a simple linear transformation of the the above column.

(Data description is from [2019 Iowa Liquor Sales dataset](https://data.iowa.gov/Sales-Distribution/2019-Iowa-Liquor-Sales/38x4-vs5h) which recording the information on liquor sales in Iowa.)
